### PR TITLE
Adds solhint

### PR DESCRIPTION
**Pull request by Agupane**
## Description

-This PR adds [solhint](https://github.com/protofire/solhint) for linting the solidity code.
-I used the recommended config rules and disabled all styling rules (and some others, like no-inline-assembly)

This is the output right now:
```
> @decentral.ee/rtoken-contracts@0.1.1 lint /home/apane/Documents/Repositorios/rtoken-contracts
> run-s lint:* && solhint contracts/**/*.sol


> @decentral.ee/rtoken-contracts@0.1.1 lint:js /home/apane/Documents/Repositorios/rtoken-contracts
> eslint . --max-warnings=0 --report-unused-disable-directives && echo '✔  Your .js files look good.'

✔  Your .js files look good.

contracts/test/ComptrollerMock.sol
    1:17  error    Compiler version 0.5.8 does not satisfy the 0.4.25 semver requirement  compiler-version
   15:88  warning  Code contains empty block                                              no-empty-blocks
   19:65  warning  Code contains empty block                                              no-empty-blocks
  119:56  warning  Open bracket must be indented by other constructions by space          bracket-align

contracts/test/InterestRateModelMock.sol
  1:17  error  Compiler version 0.5.8 does not satisfy the 0.4.25 semver requirement  compiler-version

contracts/test/RinkebyDaiFaucet.sol
  1:17  error    Compiler version 0.5.8 does not satisfy the 0.4.25 semver requirement  compiler-version
  4:32  warning  Comma must be separated from next element by space                     space-after-comma

contracts/test/TestBundle.sol
  1:17  error    Compiler version 0.5.8 does not satisfy the 0.4.25 semver requirement  compiler-version
  6:22  error    Use double quotes for string literals                                  quotes
  8:1   warning  Code contains empty block                                              no-empty-blocks

✖ 10 problems (5 errors, 5 warnings)

```

#### What is being addressed by this PR?
Add a linter to the project

#### What is the motivation for this change?
Writing code can be a difficult task. So many things that we need to look at. Hopefully there are some tools like solhint that can help us to spot obvious bugs.

#### How is the change going to be implemented?
-Adding the solhint package to the package.json file.
-Adding a solhint config to the project.

#### What packages that will be affected by this change?
None
#### What PRs will be affected by this change?
None
#### What is not addressed by this PR?
Fixes for warnings and errors found by the linter

### Note:
If you wanna add styling rules, you can add the prettier [plugin](https://github.com/fvictorio/solhint-plugin-prettier) for solhint

Regards

### CODE REVIEW

**Comment by hellwolf** [comment]
Thank you!

We are in a audit code freeze phase, will incorporate this change in next release!

**Comment by Agupane** [comment]
Thats nice, you are welcome!

**Comment by hellwolf** [comment]
Included in commit ae178cacad6bb916be53a7aebd3152d2be06a324

Thanks for the help, drop me your telegram should you wish to join our telegram developers chat!

**Comment by Agupane** [comment]
@hellwolf your welcome!, this is my telegram: `@Agupane`

**Pull request closed without merging**
